### ISSUE TITLE
Optionally omit workflow path

### ISSUE THREAD

**Issue by SolomonShorser-OICR** [CancerCollaboratory/sandbox#110]
A user can build a workflow _inside_ a docker image that is based on a SeqWare docker image, and thus contains SeqWare _and_ the workflow in a single image. If they do this, they won't need to mount an external `/workflow` directory, so this should be optional.

See: https://github.com/Consonance/consonance/blob/a237f608beddc0ddbdb1ccd559092fa0c6f846e2/pancancer-arch-3/src/main/java/info/pancancer/arch3/worker/WorkerRunnable.java#L317

**Comment by denis-yuen** [comment]
Obsolete due to adoption of CWL/Dockstore
