### ISSUE TITLE
WES Support in Consonance

### ISSUE THREAD

**Issue by alex-hancock** [CancerCollaboratory/sandbox#154]
Consonance should be compliant with the GA4GH [Workflow Execution Schema](https://github.com/ga4gh/workflow-execution-schemas) API. This will involve adding a new API implementation object in the [Consonance Webservice Application](https://github.com/Consonance/consonance/blob/develop/consonance-webservice/src/main/java/io/consonance/webservice/ConsonanceWebserviceApplication.java), and an implementation located in the [workflow directory](https://github.com/Consonance/consonance/tree/develop/consonance-webservice/src/main/java/io/swagger/workflow) in the swagger section of the webservice.

This is modeled after the nascent [TES implementation](https://github.com/Consonance/consonance/tree/develop/consonance-webservice/src/main/java/io/swagger/task) in Consonance, located [here](https://github.com/Consonance/consonance/tree/develop/consonance-webservice/src/main/java/io/swagger/task).

**Comment by achave11-ucsc** [comment]
Refer to #161 for this issue.
