### ISSUE TITLE
Different worker task command

### ISSUE THREAD

**Issue by denis-yuen** [CancerCollaboratory/sandbox#24]
Right now, the worker launch command is very static

```
           cli.addArguments(new String[] { "run", "--rm", "-h", "master", "-t", "-v", "/var/run/docker.sock:/var/run/docker.sock", "-v",
                job.getWorkflowPath() + ":/workflow", "-v", pathToINI + ":/ini", "-v", "/datastore:/datastore", "-v",
                "/home/" + this.userName + "/.ssh/gnos.pem:/home/ubuntu/.ssh/gnos.pem", "pancancer/seqware_whitestar_pancancer:1.1.1",
                "seqware", "bundle", "launch", "--dir", "/workflow", "--ini", "/ini", "--no-metadata" });
```

I'd like to see more possible customization, for example if we wanted to run whitestar in, say, --whitestar-parallel, with a different mounted ~/seqware/settings, etc. 

However, rather than going down the path of more parameters and more specificity, let's see if we can think of a way to generalize this.

**Comment by SolomonShorser-OICR** [comment]
Working on this...

**Comment by SolomonShorser-OICR** [comment]
See: https://github.com/CancerCollaboratory/sandbox/pull/32

**Comment by denis-yuen** [comment]
This is functional as of 1.1-beta.3
