### ISSUE TITLE
Split reporting to a separate module/jar

### ISSUE THREAD

**Issue by SolomonShorser-OICR** [CancerCollaboratory/sandbox#30]
This file is the logback config file:

https://github.com/CancerCollaboratory/sandbox/blob/19cb6e57d54ae20581ea49071e25eec33fdce977/pancancer-arch-3/src/main/resources/logback.xml

it specifies a single location to log messages to. With the arch3 jar file containing functionality for Worker, JobGenerator, Coordinator, and Reporting, this could be a problem when JobGenerator, Coordinator, and Reporting are all run on a single machine.
The biggest possible conflict is between Reporting and JobGenerator/Coordinator. 
One solution is to try to associate package name patterns with different logging files, but this causes problems with utility methods that are in packages that are not specific for any of the major tasks named above.

A better solution is to split the Reporting functionality to a separate module / jar file so it can have it's own configuration, separate from Generator/Coordinator.

There is little concern about Worker being included in the same component as Generator/Coordinator (wrt logging) because the Worker functionality is not used on the same machine that Generator/Coordinator functionality is used. If this ever changes, then splitting out a new module should be considered.

**Comment by denis-yuen** [comment]
Completed, split into a separate module.
