### ISSUE TITLE
Worker in endless mode needs to do cleanup 

### ISSUE THREAD

**Issue by denis-yuen** [CancerCollaboratory/sandbox#78]
When in normal operation, we rely upon the instances being killed to deal with build up of cruft. 
In endless mode, we don't have this luxury, so clean up the datastore's contents between jobs (failed or not.

This probably needs sudo since there is no guarantee who owns the files left by workflows. 

@oicr-vchung

**Comment by denis-yuen** [comment]
Also, the current worker build dies on failure which is not ideal

**Comment by oicr-vchung** [comment]
The /home/ubuntu/, /datastore/, /workflows/ and /tmp/ folders may need to be cleared, but there were files in there originally, and the setup/provision scripts may need to be rerun. I believe there are also docker containers spawned from images that should not be reused.

Perhaps clean-up would be simpler to do if workflows were self-contained (run strictly within docker images/containers) or restricted to only write to certain exclusive areas in the arch3 folder hierarchy?

**Comment by denis-yuen** [comment]
I think /datastore should be sufficient. I agree that ideally we would do /tmp, but that would be hard to do cleanly. Docker containers should be run with `--rm` and be autocleaned, so I think we're safe on that front. 
Technically, there is stuff like /var/log which will gradually fill up but since we're not shooting for this model long-term, I don't think we have to go that far.
