### ISSUE TITLE
Cleanup of worker jams up tests in development environment

### ISSUE THREAD

**Issue by denis-yuen** [CancerCollaboratory/sandbox#81]
sudo with a password used by the worker to cleanup /datastore hangs the tests
This shouldn't be called anyways and should be mocked

Current workaround: sudo vim (enter password) then mvn release:prepare/perform before a timeout

**Comment by SolomonShorser-OICR** [comment]
Which test is this occurring with?

**Comment by SolomonShorser-OICR** [comment]
Is this happening when the shutdown hook is called?
https://github.com/Consonance/consonance/blob/3dde656ba3a8966baa96d1aac79ded2074f17d86/pancancer-arch-3/src/main/java/info/pancancer/arch3/worker/Worker.java#L43
