### ISSUE TITLE
Log all messages to/from queue to a separate file

### ISSUE THREAD

**Issue by SolomonShorser-OICR** [CancerCollaboratory/sandbox#91]
It is difficult to read through the arch3.log file when it has been filled with messages from the coordinator from several nodes for a whole day. Maybe the messages could be redirected to a separate log file to make processing the main application's log file easier?

**Comment by denis-yuen** [comment]
+1

**Comment by SolomonShorser-OICR** [comment]
Better yet, only log them in DEBUG mode: https://github.com/Consonance/consonance/commit/542b9cae926d8d666d43a69d12813cb812586c74

@denis-yuen : will this automatically get merged into the Consonance 2 branch or do you need to cherry-pick this commit manually?

**Comment by denis-yuen** [comment]
I'll need to cherry-pick unless you make a pull request against each branch separately.

**Comment by SolomonShorser-OICR** [comment]
This was released in https://github.com/Consonance/consonance/releases/tag/1.1-rc.1
